export const message={
    missingFieldMessage:"Please provide all the fields",
    userAlreadyExist:"User already exist",
    userCreatedMessage:"User registered successfully",
    userNotFoundMessage:"User not found, register first", 
    idNotFoundMessage:"Id not found ",
    userAlreadyVerified:"User is already verified",
    otpAttemptsExceededMessage:"OTP attempts are exceeded,please try after some time",
    otpNotFoundMessage:"Please provide an otp",
    otpExpireMessage:"OTP expired,please resend",
    invalidOtpMessage:"OTP entered is incorrect",
    userVerifiedMessage:"User verified successfully",
    otpSendMessage:"OTP sent successfully",
    userNotVerifiedMessage:"Please Verify your account",
    loginLockedMessage: "Login attempts exceeded, Please try again later",
    badAuthMessage: "Invalid email or password",
    loginSuccessfulMessage:"Login Successful",
    otpVerifiedMessage:"OTP verified successfully",
    passwordChangeMessage:"Password updated Successfully",
    userProfileFoundMessage:"user profile found",
    userProfileUpdatedMessage:"User profile updated successfully",
    logoutMessage:"Logout successful",
    userDeletedMessage:"User deleted successfully",
    addressAddMessage:"Address added successfully",
    addressRemovedMessage:"Address removed successfully",
    addressSetMessage:"Default address updated successfully",
    addressNotFoundMessage:"Address not found",
    getAddressMessage:"Addresses retrieved successfully",
    unAuthorizedMessage:"Please login to access",
    retailerNotFoundMessage:"Retailer not found",
    retailerAlreadyExistMessage:"Retailer already exist",
    retailerCreatedMessage:"Retailer created successfully",
    retailerVerifiedMessage:"Retailer is already verified",
    retailerNotVerifiedMessage:"Retailer is not verified",
    retailerProfileFoundMessage:"Profile found successfully",
    retailerProfileUpdatedMessage:"Profile updated successfully",
    retailerDeletedMessage:"Retailer Deleted Successfully",
    noProductMessage:"No products found",
    productFetchedMessage:"Products fetched successfully",
    productAddedMessage:"Product added successfully",
    productsFoundMessage:"Products Found Successfully",
    productNotFoundMessage:"Product not found",
    invalidRetailerMessage:"Please access with correct Retailer",
    productFoundMessage:"Product Found Successful",
    productRemovedMessage:"Product Removed Successfully",
    productUpdatedMessage:"Product updated successfully",
    reviewNotFoundMessage:"Review not found",
    reviewCreatedMessage:"Review uploaded successfuly",
    reviewFoundMessage:"Review found successfully",
    accessInvalidMessage:"Invalid action",
    reviewDeletedMessage:"Review deleted successfully",
    reviewsFoundMessage:"Reviews found Successful",
    reviewUpdatedMessage:"Review Updated Successful",
    productAlreadyMessage:"Product is Alreay present",
    productAddedToWishListMessage:"Product Added Successful",
    wishListNotFoundMessage:"WishListNotFound",


}